apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tipsbank-web
  name: nginx-conf-v2
  labels:
    app: web
    kubernetes.io/name: web
    kubernetes.io/part-of: tipsbank
data:
  nginx.conf: |
    worker_processes auto;
    pid /tmp/nginx.pid;
    events { worker_connections 1024; }
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      sendfile on;
      keepalive_timeout 65;
      client_body_temp_path /tmp/client_body;
      proxy_temp_path       /tmp/proxy;
      fastcgi_temp_path     /tmp/fastcgi;
      uwsgi_temp_path       /tmp/uwsgi;
      scgi_temp_path        /tmp/scgi;

      resolver 10.100.0.10 valid=10s ipv6=off;

      server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        location = /healthz {
          access_log off;
          return 200 "ok\n";
        }

        location /api/contas/ {
          set $up http://api-contas.tipsbank-contas.svc.cluster.local:8080;
          rewrite ^/api/contas/(.*) /$1 break;
          proxy_pass $up;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/transacoes/ {
          set $up http://api-transacoes.tipsbank-transacoes.svc.cluster.local:8080;
          rewrite ^/api/transacoes/(.*) /$1 break;
          proxy_pass $up;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/auditoria/ {
          set $up http://auditoria.tipsbank-auditoria.svc.cluster.local:8080;
          rewrite ^/api/auditoria/(.*) /$1 break;
          proxy_pass $up;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
          try_files $uri $uri/ /index.html;
        }
      }
    }
