apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tipsbank-transacoes
  name: transacoes-config
  labels:
    app: api-transacoes
    app.kubernetes.io/name: api-transacoes
    app.kubernetes.io/part-of: tipsbank
data:
  CONTAS_URL: "http://api-contas.tipsbank-contas.svc.cluster.local:8080"
  AUDITORIA_URL: "http://auditoria.tipsbank-auditoria.svc.cluster.local:8080"
  APP_VERSION: "v1"
  LOG_LEVEL: "INFO"
