apiVersion: v1
kind: Secret
metadata:
  namespace: tipsbank-transacoes
  name: transacoes-secret
  labels:
    app: api-transacoes
    app.kubernetes.io/name: api-transacoes
    app.kubernetes.io/part-of: tipsbank
type: Opaque
stringData:
  DB_URL: "postgresql+psycopg://tipsbank:tipsbank@postgres-service.tipsbank-conta\
    s.svc.cluster.local:5432/tipsbank"
