apiVersion: v1
kind: Secret
metadata:
  namespace: tipsbank-contas
  name: contas-secret
  labels:
    app.kubernetes.io/name: api-contas
    app.kubernetes.io/part-of: tipsbank
type: Opaque
stringData:
  DB_URL: "postgresql+psycopg://tipsbank:tipsbank@postgres-service.tipsbank-conta\
    s.svc.cluster.local:5432/tipsbank"
  LOG_LEVEL: "INFO"
