apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-transacoes
  namespace: tipsbank-transacoes
  labels:
    app: api-transacoes
    app.kubernetes.io/name: api-transacoes
    app.kubernetes.io/part-of: tipsbank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-transacoes
  template:
    metadata:
      labels:
        app: api-transacoes
        app.kubernetes.io/name: api-transacoes
        app.kubernetes.io/part-of: tipsbank
    spec:
      initContainers:
        - name: init-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres-service.tipsbank-contas.svc.cluster.local 5432; do
                echo "Verificando conexão com Postgres..."
                sleep 3
              done
        - name: init-api-contas
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until wget -q --spider http://api-contas.tipsbank-contas.svc.cluster.local:8081/health/live; do
                echo "Verificando se api-contas esta live..."
                sleep 3
                done
      containers:
        - name: api-transacoes
          image: felipestaypuff/tipsbank-api-transacoes:v1.0.0
          ports:
            - containerPort: 8080
              name: api-transacoes
          envFrom:
            - secretRef:
                name: transacoes-secret
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: api-transacoes
  namespace: tipsbank-transacoes
  labels:
    app: api-transacoes
    app.kubernetes.io/name: api-transacoes
    app.kubernetes.io/part-of: tipsbank
spec:
  type: ClusterIP
  selector:
    app: api-transacoes
  ports:
    - port: 8082
      targetPort: 8080
      name: api-transacoes
