apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tipsbank-slo-alerts
  namespace: tipsbank-monitoring
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: tipsbank-slo-alerts
    app.kubernetes.io/part-of: tipsbank
spec:
  groups:
    - name: tipsbank.availability
      interval: 30s
      rules:
        - alert: TipsBankApiDown
          expr: up{namespace=~"api-.*"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "API TipsBank indisponível"
            description: "O job {{ $labels.job }} está down há mais de 2 minutos. Namespace: {{ $labels.namespace }}"
