apiVersion: v1
kind: PersistentVolume
metadata:
  name: auditoria-efs-pv
spec:
  capacity:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d5b539e1d48f267d
  mountOptions:
    - tls

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auditoria-pvc
  namespace: tipsbank-auditoria
  labels:
    app: auditoria
    app.kubernetes.io/name: auditoria
    app.kubernetes.io/part-of: tipsbank
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: auditoria-efs-pv
  storageClassName: ""
