apiVersion: v1
kind: Secret
metadata:
  namespace: tipsbank-contas
  name: postgres-secret
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: tipsbank
type: Opaque
stringData:
  POSTGRES_USER: tipsbank
  POSTGRES_PASSWORD: tipsbank
  POSTGRES_DB: tipsbank
